/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchematicEditorRouteImport } from './routes/schematic-editor'
import { Route as IndexRouteImport } from './routes/index'

const SchematicEditorRoute = SchematicEditorRouteImport.update({
  id: '/schematic-editor',
  path: '/schematic-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schematic-editor': typeof SchematicEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schematic-editor': typeof SchematicEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schematic-editor': typeof SchematicEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/schematic-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schematic-editor'
  id: '__root__' | '/' | '/schematic-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchematicEditorRoute: typeof SchematicEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schematic-editor': {
      id: '/schematic-editor'
      path: '/schematic-editor'
      fullPath: '/schematic-editor'
      preLoaderRoute: typeof SchematicEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchematicEditorRoute: SchematicEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
